### ISSUE TITLE
Add a filter option on status

### ISSUE THREAD

**Issue by thoda-dev** [Jericho1060/DU-Industry-HUD#10]
Add a control to display only machines that currently has a specified status

**Comment by Mustache84** [comment]
oooh this looks nice!

**Comment by Mustache84** [comment]
Before I make a feature request, do you know if you can pull the wonky errors out these days? like the server error stuff?

**Comment by thoda-dev** [comment]
it seems some of the server error are captured and displayed as jammed but some other not
and i can't do more on that side actually

**Comment by thoda-dev** [comment]
hard to do it at the moment becuase it would require to get the status of all machines in a single category.
that could cause CPU load Errors.

In Stand By at the moment
