### ISSUE TITLE
Feature Request: Toggle to Stop Updating

### ISSUE THREAD

**Issue by Mustache84** [Jericho1060/DU-Industry-HUD#11]
Current state: in always updates whatever section/page you're on. 

Feature request: Have the ability to toggle the updating of boards on/off. 

Reason: When I'm floating around the factory working on a machine that I highlighted, the stutters from the updates make it hard to do my work.

**Comment by thoda-dev** [comment]
easy to do i'll do that first

**Comment by thoda-dev** [comment]
Done on the Beta Branch - will be sent to main soon
-> just the master program needs an update
