### ISSUE TITLE
Data collector lua simply stops on line 33 (MyJson.parse) without error message

### ISSUE THREAD

**Issue by DorianTheGrey** [Jericho1060/DU-Industry-HUD#12]
Did exactly what was written in the installation instruction, but encountered a weird problem:

In unit.start() of the collector, lines 30+ the MyJson.parse command seems to stop the script without throwing an error. I verified by adding system.prints. The second one never gets displayed. Therefore, the collector doesn't save any data to the databank, so the master displays the devices (but of course the master thinks they are not connected).

[Lines 30+ ...]

if databank ~= nil then
    local refresh_id_list = {}
    system.print("DISPLAYED")
    if databank.hasKey("refresh_id_list") then
        refresh_id_list = MyJson.parse(databank.getStringValue("refresh_id_list"))
    end
    system.print("NEVER DISPLAYED")
    for i = 1, #industries, 1 do

[...]

Any ideas?

**Comment by DorianTheGrey** [comment]
The user was the problem. The DB was not connected properly. But I am surprised databank wasn't nil then.

**Comment by thoda-dev** [comment]
Hi, i'm not sure to understand what heppened to you
Just to let you know, the master program is sending to all datacollection program the list of machines currently displayed to make sure only theses ones a refresh to avoid any CPU Load error

this is not complettely blocking the data colection board, it is starting because i can't know where the machine are connected. It's just doing nothing.

**Comment by DorianTheGrey** [comment]
Hi mate, yes, I understand the concepts, it's a really nice lua, thanks a lot for it. 👍 

What happened to me was that I forgot to link the databank, and still the statment "if databank ~= nil" is true, so the code afterwards got executed (my first system.print was firing up), but afterwards nothing happened. So I just was confused. Linking up the databank makes it work perfectly now. Thanks again!

**Comment by thoda-dev** [comment]
tested, not happening to me. strange
