### ISSUE TITLE
Hud not work

### ISSUE THREAD

**Issue by Vardenus** [Jericho1060/DU-Industry-HUD#20]
Hi I don't know if it's because of a new upgrade or I'm doing something wrong, but although the monitoring itself works, I can't control the machines in any way. I have tried many combinations. It does not work. you can check it ?

**Comment by thoda-dev** [comment]
> Hi I don't know if it's because of a new upgrade or I'm doing something wrong, but although the monitoring itself works, I can't control the machines in any way. I have tried many combinations. It does not work. you can check it ?

Hi, i just tested it and everything is working fine for me.

I know NQ made changes on emitter and receiver. Event if it wont be used, you can try to set a channel to the emitter, it seems the game don't like empty values here.

right click on the emitter linked to the board, and click on Set Channel

![image](https://user-images.githubusercontent.com/28439359/147688655-30a32946-a73d-4f81-b29d-0606eb9b3c2f.png)

Then put any value in the text field (i added "Echo") and save it.

If you still have the problem, it may be a setup problem.
