### ISSUE TITLE
Can't get it to work right

### ISSUE THREAD

**Issue by FairfieldTekLLC** [Jericho1060/DU-Industry-HUD#21]
I've been trying to set this up for a while.  I set up the first remote control board for chemical, and it was able to turn stuff on and off.
I then set up the next one w/ a new programming for refining and added a new reciever, set the channel,added a databank, connected it to the main board and this board and tried to toggle the industry and nothing happened.

What did I do wrong?

**Comment by thoda-dev** [comment]
Hi, hard to say with not so much details.
![image](https://user-images.githubusercontent.com/28439359/152812549-aba9e81d-3a94-4409-afce-e471b808eea9.png)
Here a draw on how to connect everything

**Comment by FairfieldTekLLC** [comment]
Perfect, works great now

**Comment by thoda-dev** [comment]
Nice to hear, there was a bug in the english doc, the picture was missing i added it.
