### ISSUE TITLE
Metal Work Remote control doesn't seem to be working

### ISSUE THREAD

**Issue by FairfieldTekLLC** [Jericho1060/DU-Industry-HUD#22]
I've configured the Glass Factories, Recyclers, and chemical factories no problem but no matter what I do for metal work it doesn't seem to work.

I place a programming board
I paste the script to the board
I place a databank
I connect the programming board to the databank
I connect the main board to the databank
I place a receiver, set it to 'receiver_metalworks'
I place a Relay,
Connect Receiver to relay, relay to programming board
I connect a metal work to the programming board
Restart the main board
I find the metal work factory and press ALT+1 to stop it.
The relay blinks
nothing happens.

What did I do wrong?

**Comment by FairfieldTekLLC** [comment]
The machine ID is 947, I hooked up other metal work factories and I can toggle them on the same board, really confused what it doesn't like about this factory.  I can show you in game if u want.

**Comment by thoda-dev** [comment]
Hi, Metalworks are working exactly the same way all other industries.
If it's not working especially on that one, that probabaly mean you have something missing, i can help you for that.

Be sure you connected the receiver the good way, there is two possibilities to do it and also the channel is really the same on both sides, without typo.
