### ISSUE TITLE
Industry table view not sorting by recipe as it used to

### ISSUE THREAD

**Issue by smooreace** [Jericho1060/DU-Industry-HUD#26]
In an earlier version, the table view of the industry list used to be sorted by machine name. If there was no assigned name, then the type of machine was the default name. This made finding a specific machine very easy. It made for determining if a given element/product/whatever was being made. And now that storage is being listed, it too would make it far easier to find a specific container. Unfortunately, at some point, that default action has vanished. Was this intentional? Or an oversight?

**Comment by thoda-dev** [comment]
That's true, i rewrote the whole code for that version and complettely forget about doing that, currently it's sorted by ID.
I'll see to add a new sorting for the machines in the table view.

@smooreace Do you prefer a sorting by Machine Name or by product ?

**Comment by smooreace** [comment]
Technically, product would be easier. But because of the old version we got in the habit of renaming all of our machines to match the product being made. So we could go either way. I'de think product would be most useful for the general population though... just my 2 cents. Thanks!

**Comment by thoda-dev** [comment]
humm, ok, i'll check if i can add several sorting, like for the view with al+7 or alt+8, i may be able to add a sorting option with alt+6 on table view.

I have several things to check before i'll come back to you here to tell what i can do

**Comment by smooreace** [comment]
Even a sort via LUA param would work

**Comment by smooreace** [comment]
But we have much bigger issues! I think its time for a room addition!
![image](https://user-images.githubusercontent.com/35540547/198711737-07751200-bbd2-4f1e-a6d4-452f46faa08a.png)

**Comment by thoda-dev** [comment]
so that's another issue, i will not answer it here, create another ticket if you want, but you have two lua parameters to deal with CPU load errors

**Comment by thoda-dev** [comment]
Sorting option have been added to v4.1.0 with 3 types of sorting and a lua parameter to select the default one.
