### ISSUE TITLE
Feature Request: Keep Maintain Amount On Restart

### ISSUE THREAD

**Issue by Mustache84** [Jericho1060/DU-Industry-HUD#7]
Current behavior: You hit ALT+1 to stop the target machine. You then hit ALT+1 to start the target machine. The script doesn't allow you to keep the current maintain rate and will start the machine with only the infinite craft option. 

Request: Allow an option that just restarts the machine vs erasing maintain/make numbers. The same behavior as if you were to open the element manually and click "stop" and then "start"

**Comment by thoda-dev** [comment]
Hi, than you for your message, this is planned that when you hit the bath or maintain action with a 0 value, you are restarting by keeping the old amount
this should be deployed today or tomorrow

i'll answer here again when it will be ready

**Comment by thoda-dev** [comment]
I must put that in stand by at the moment, the way i found to do it seems to not work like it should and starting infinte most of time.
I have to search for a new solution to that before.

**Comment by Mustache84** [comment]
Righto! no worries, appreciate it!
