### ISSUE TITLE
Feature Request: Client Optimization

### ISSUE THREAD

**Issue by Mustache84** [Jericho1060/DU-Industry-HUD#8]
Current State: When the HUD is targeting a specific filter/industry type, such as Electronics Industries Elements, it pings every single element all at once. Currently, anecdotally, I have 97 elements on this filter type and every 1s it freezes the game. Even if I were to delay the querying of elements, it freezes every time b/c it's running 97 scripts. 

Optimization Request: When you are on Page 1 or Page 2 of a filter type, have the query system only ping those systems listed to reduce the client load. Example: Electronics Industries are filtered and the client is viewing page 1 with 20 elements in the list. The query will only ping those 20 elements in the list thus limiting the game clients' resource requests and optimizing performance.

**Comment by Mustache84** [comment]
Current stack, for reference, of Electronics Industry: 
![image](https://user-images.githubusercontent.com/28316664/96150809-bf4ab080-0ed8-11eb-8e9e-279c37d3d410.png)

**Comment by thoda-dev** [comment]
It was done on the last update
Both Master program and Data Collection Program need to be updated.

Even if the remote board is starting, nothing is done.

This is also solving all CPU load problems.

**Comment by Mustache84** [comment]
awesome!
